### ISSUE TITLE
IMA Voltage

### ISSUE THREAD

**Issue by ekoninsp** [fedorenkoalex/CIVP30OBD_BT#2]
Hi.. Alex,
if I use universal car scanner that support to read Honda P30 ECU like : autoboss, xtools etc.. 
I can see output of IMA sensor/voltage (settings for the fuel and air mixture in openloop system).
Based on your writing about ECU response on P30. Do you know how can we get the output of IMA voltage value?
--Thank you..

**Comment by fedorenkoalex** [comment]
Hi, @ekoninsp 
I worked on this project 5 years ago and did not investigate this topic for a long time.
I am not sure that I can help you with this.
I don’t even have a car anymore to test this😀
